server:
  port: 8080

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

application:
  packer:
    timeoutMilliseconds: 5000

logging:
  level:
    org:
      springframework:
        security: DEBUG