spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

application:
  packer:
    timeoutMilliseconds: 5000
    systemLengthUnit: METRIC_MILLIMETER
    systemWeightUnit: METRIC_GRAM