server:
  port: 8080

application:
  packer:
    timeoutMilliseconds: 5000

#logging:
#  level:
#    org:
#      springframework: DEBUG
#    reactor:
#      netty:
#        http:
#          client:
#            HttpClient: DEBUG